import { useEffect, useRef, useState, type FormEvent } from "react";
import { ArrowUpRight, Bot, CircleAlert, CircleCheck, Globe2, LoaderCircle, LogOut, MessageCircle, Send, Sparkles, Square } from "lucide-react";
import { ApiError } from "./api/client";
import { listCompanies, createCompany } from "./api/companies";
import { askCompany } from "./api/chat";
import { cancelCrawl, listCrawlJobs, startCrawl } from "./api/crawl";
import { useAuth } from "./hooks/useAuth";
import { useCurrentTab } from "./hooks/useCurrentTab";
import { useCrawlStatus } from "./hooks/useCrawlStatus";
import { companyMatchesSite } from "./utils/site";
import type { ChatResponse, Company, CrawlJob } from "./types";

type Message = { role: "user" | "assistant"; text: string; sources?: ChatResponse["sources"] };
const terminal = new Set(["COMPLETED", "FAILED", "CANCELLED"]);
const errorMessage = (error: unknown) => error instanceof ApiError && error.status === 401 ? "Your session expired. Please sign in again." : error instanceof Error ? error.message : "Something went wrong. Please try again.";
const duration = (seconds: number | null) => seconds == null ? "—" : `${Math.floor(seconds / 60)}m ${Math.round(seconds % 60)}s`;

function Login({ onLogin }: { onLogin: (email: string, password: string) => Promise<void> }) {
  const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  async function submit(e: FormEvent) { e.preventDefault(); setLoading(true); setError(""); try { await onLogin(email, password); } catch (err) { setError(errorMessage(err)); } finally { setLoading(false); } }
  return <main className="login"><div className="logo"><span>F</span> fieldnote</div><div className="login-kicker">Website AI</div><h1>Ask the web<br /><i>better.</i></h1><p className="muted">A grounded assistant for the website you’re viewing.</p><form onSubmit={submit}><label>Email<input type="email" required value={email} onChange={e => setEmail(e.target.value)} placeholder="you@company.com" autoComplete="email" /></label><label>Password<input type="password" required value={password} onChange={e => setPassword(e.target.value)} placeholder="Your password" autoComplete="current-password" /></label>{error && <div className="alert"><CircleAlert size={15} />{error}</div>}<button className="button primary" disabled={loading}>{loading ? "Signing in…" : "Sign in"}<ArrowUpRight size={16} /></button></form></main>;
}

function App() {
  const auth = useAuth();
  if (!auth.token) return <Login onLogin={auth.signIn} />;
  return <Assistant onLogout={auth.signOut} />;
}

function Assistant({ onLogout }: { onLogout: () => Promise<void> }) {
  const site = useCurrentTab(); const [companies, setCompanies] = useState<Company[]>([]); const [company, setCompany] = useState<Company | null>(null); const [latest, setLatest] = useState<CrawlJob | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [jobId, setJobId] = useState<number | null>(null); const [messages, setMessages] = useState<Message[]>([]); const crawl = useCrawlStatus(company?.id ?? null, jobId); const [question, setQuestion] = useState(""); const [chatLoading, setChatLoading] = useState(false); const chatEnd = useRef<HTMLDivElement>(null);
  useEffect(() => { if (!site) return; setLoading(true); listCompanies().then(all => { setCompanies(all); setCompany(all.find(item => companyMatchesSite(item, site)) ?? null); }).catch(e => setError(errorMessage(e))).finally(() => setLoading(false)); }, [site]);
  useEffect(() => { if (!company) return; listCrawlJobs(company.id).then(jobs => setLatest(jobs[0] ?? null)).catch(e => setError(errorMessage(e))); }, [company]);
  useEffect(() => { if (crawl.job) { setLatest(crawl.job); if (terminal.has(crawl.job.status)) setJobId(null); } }, [crawl.job]);
  useEffect(() => { chatEnd.current?.scrollIntoView({ behavior: "smooth" }); }, [messages, chatLoading]);
  async function addAndCrawl() { if (!site) return; try { const created = await createCompany({ name: site.hostname, website_url: site.url }); setCompany(created); const job = await startCrawl(created.id); setJobId(job.job_id); } catch (e) { setError(errorMessage(e)); } }
  async function send(e: FormEvent) { e.preventDefault(); const text = question.trim(); if (!text || !company || chatLoading) return; setQuestion(""); setMessages(current => [...current, { role: "user", text }]); setChatLoading(true); try { const answer = await askCompany(company.id, text); setMessages(current => [...current, { role: "assistant", text: answer.answer, sources: answer.sources }]); } catch (e) { setMessages(current => [...current, { role: "assistant", text: e instanceof ApiError && e.status === 502 ? "The AI service is temporarily unavailable. Please try again." : errorMessage(e) }]); } finally { setChatLoading(false); } }
  async function stop() { if (!company || !jobId) return; try { await cancelCrawl(company.id, jobId); } catch (e) { setError(errorMessage(e)); } }
  const supported = Boolean(site); const ready = Boolean(company && (latest?.status === "COMPLETED" || crawl.job?.status === "COMPLETED")); const preparing = Boolean(jobId && crawl.job && !terminal.has(crawl.job.status));
  return <main className="assistant"><header><div className="logo"><span>F</span> fieldnote</div><button className="logout" onClick={onLogout}><LogOut size={14} /></button></header><div className="site"><div className={`site-icon ${supported ? "live" : ""}`}><Globe2 size={18} /></div><div><div className="label">Current website</div><strong>{site?.hostname ?? "Unsupported page"}</strong></div><div className={`connection ${ready ? "ready" : ""}`}><span />{ready ? "Ready" : preparing ? "Preparing" : supported ? "Not connected" : "Unavailable"}</div></div>{error && <div className="alert"><CircleAlert size={15} />{error}<button onClick={() => setError("")}>×</button></div>}{loading ? <div className="center"><LoaderCircle className="spin" size={22} /> Checking this website…</div> : !supported ? <Empty icon={<CircleAlert />} title="This page isn't supported" copy="Open a normal http or https website to use Website AI." /> : company ? <><div className="company-name"><span className="label">Connected company</span><h1>{company.name}</h1></div>{preparing && crawl.job ? <CrawlCard job={crawl.job} onCancel={stop} /> : !ready ? <PrepareCard job={latest} onStart={async () => { try { const job = await startCrawl(company.id); setJobId(job.job_id); } catch (e) { setError(errorMessage(e)); } }} /> : <Chat messages={messages} question={question} setQuestion={setQuestion} loading={chatLoading} onSend={send} endRef={chatEnd} />}</> : <Empty icon={<Sparkles />} title="This website isn't connected yet" copy="Prepare it once, then ask questions grounded in its pages." action={<button className="button primary" onClick={addAndCrawl}>Add & crawl <ArrowUpRight size={16} /></button>} />}</main>;
}

function Empty({ icon, title, copy, action }: { icon: React.ReactNode; title: string; copy: string; action?: React.ReactNode }) { return <section className="empty"><div className="empty-icon">{icon}</div><h2>{title}</h2><p>{copy}</p>{action}</section>; }
function PrepareCard({ job, onStart }: { job: CrawlJob | null; onStart: () => Promise<void> }) { return <section className="prepare"><div className="prepare-icon"><Sparkles size={21} /></div><h2>Prepare this website<br />for AI chat</h2><p>{job?.status === "FAILED" ? job.error || "The previous crawl failed." : "We’ll safely crawl its public pages and build a searchable knowledge base."}</p><button className="button primary" onClick={onStart}>{job?.status === "FAILED" ? "Try again" : "Add & crawl"}<ArrowUpRight size={16} /></button></section>; }
function CrawlCard({ job, onCancel }: { job: CrawlJob; onCancel: () => Promise<void> }) { return <section className="crawl"><div className="crawl-title"><div><div className="label">Website preparation</div><h2>{job.status === "QUEUED" ? "Queued" : "Crawling pages"}</h2></div><span className="pulse"><span />{job.status}</span></div><div className="stats"><Stat label="Discovered" value={job.pages_discovered} /><Stat label="Crawled" value={job.pages_crawled} /><Stat label="Indexed" value={job.pages_indexed} /><Stat label="Failed" value={job.pages_failed} /></div><div className="substats"><span>New {job.pages_new}</span><span>Changed {job.pages_changed}</span><span>Unchanged {job.pages_unchanged}</span><span>Deactivated {job.pages_deactivated}</span></div><button className="cancel" onClick={onCancel}><Square size={13} /> Cancel crawl</button></section>; }
function Stat({ label, value }: { label: string; value: number }) { return <div><span>{label}</span><strong>{value}</strong></div>; }
function Chat({ messages, question, setQuestion, loading, onSend, endRef }: { messages: Message[]; question: string; setQuestion: (value: string) => void; loading: boolean; onSend: (event: FormEvent) => Promise<void>; endRef: React.RefObject<HTMLDivElement> }) { return <section className="chat"><div className="chat-intro"><MessageCircle size={18} /><div><div className="label">Company knowledge</div><h2>Ask anything about this website.</h2></div></div><div className="messages">{messages.length === 0 && <div className="suggestion">“What does this website offer?”</div>}{messages.map((message, index) => <div className={`message ${message.role}`} key={`${message.role}-${index}`}><div className="message-mark">{message.role === "assistant" ? <Bot size={14} /> : "You"}</div><div className="message-body"><p>{message.text}</p>{message.sources?.map(source => <a className="source" href={source.url} target="_blank" rel="noreferrer" key={source.url}><Globe2 size={12} />{source.title || source.url}<ArrowUpRight size={12} /></a>)}</div></div>)}{loading && <div className="message assistant"><div className="message-mark"><Bot size={14} /></div><div className="thinking"><span /><span /><span /></div></div>}<div ref={endRef} /></div><form className="composer" onSubmit={onSend}><textarea value={question} onChange={e => setQuestion(e.target.value)} onKeyDown={e => { if (e.key === "Enter" && !e.shiftKey) { e.preventDefault(); e.currentTarget.form?.requestSubmit(); } }} placeholder="Ask a question…" rows={2} disabled={loading} /><button disabled={!question.trim() || loading} aria-label="Send"><Send size={16} /></button></form><div className="chat-note">Answers are grounded in indexed website content.</div></section>; }
export default App;
