"""Add attempt_count to crawl_jobs

Revision ID: 4207836894c0
Revises: f168f90a87a5
Create Date: 2026-08-31 00:55:37.030878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4207836894c0'
down_revision: Union[str, Sequence[str], None] = 'f168f90a87a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crawl_jobs', sa.Column('attempt_count', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('crawl_jobs', 'attempt_count')
    # ### end Alembic commands ###
