"""add crawl job counters

Revision ID: f168f90a87a5
Revises: 
Create Date: 2026-08-30 23:04:53.316967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f168f90a87a5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crawl_jobs', sa.Column('pages_discovered', sa.Integer(), nullable=False))
    op.add_column('crawl_jobs', sa.Column('pages_indexed', sa.Integer(), nullable=False))
    op.add_column('crawl_jobs', sa.Column('pages_failed', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('crawl_jobs', 'pages_failed')
    op.drop_column('crawl_jobs', 'pages_indexed')
    op.drop_column('crawl_jobs', 'pages_discovered')
    # ### end Alembic commands ###
